replicaCount: 1
image:
  apiGateway:
    repository: anwirisme/spring-petclinic-api-gateway
    tag: main
  discoveryServer:
    repository: anwirisme/spring-petclinic-discovery-server
    tag: main
  customersService:
    repository: anwirisme/spring-petclinic-customers-service
    tag: v2.1.0
  vetsService:
    repository: anwirisme/spring-petclinic-vets-service
    tag: main
  visitsService:
    repository: anwirisme/spring-petclinic-visits-service
    tag: main
  genaiService:
    repository: anwirisme/spring-petclinic-genai-service
    tag: main
  adminServer:
    repository: anwirisme/spring-petclinic-admin-server
    tag: main
  configServer:
    repository: anwirisme/spring-petclinic-config-server
    tag: main
service:
  discoveryServer:
    port: 8761
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 30090
  configServer:
    port: 8888
    nodePort: 30088
  apiGateway:
    port: 8080
    nodePort: 30080
