replicaCount: 1
image:
  apiGateway:
    repository: anwirisme/spring-petclinic-api-gateway
    tag: 24e6a46
  discoveryServer:
    repository: anwirisme/spring-petclinic-discovery-server
    tag: main
  customersService:
    repository: anwirisme/spring-petclinic-customers-service
    tag: 24e6a46
  vetsService:
    repository: anwirisme/spring-petclinic-vets-service
    tag: 24e6a46
  visitsService:
    repository: anwirisme/spring-petclinic-visits-service
    tag: 24e6a46
  genaiService:
    repository: anwirisme/spring-petclinic-genai-service
    tag: main
  adminServer:
    repository: anwirisme/spring-petclinic-admin-server
    tag: 24e6a46
  configServer:
    repository: anwirisme/spring-petclinic-config-server
    tag: 24e6a46
service:
  discoveryServer:
    port: 8761
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 30090
  configServer:
    port: 8888
    nodePort: 30088
  apiGateway:
    port: 8080
    nodePort: 30080
  zipkin:
    port: 9411
    nodePort: 30084
  prometheus:
    port: 9090
    nodePort: 30093
  grafana:
    port: 3000
    nodePort: 30096
loki:
  namespace: dev
